columns:
  main:
    width: 2/3
    sections:
      pages:
        label: Pages
        type: pages
      configs:
        label: Configs
        type: pages
        templates: languages

  sidebar:
    width: 1/3
    fields:
      socialLinks:
        label: Social Links
        type: structure
        fields:
          url:
            label: URL
            type: text
          iconName:
            label: Icon Name
            type: slug
